language: ruby

sudo: false

before_install:
  - add-apt-repository ppa:zero-tsuki/ppa -y
  - apt-get update -q
  - apt-get install libapngasm swig

rvm:
  - 2.0.0
  - 2.1
  - 2.2.3
  - ruby-head
  - rbx
  - jruby-head

script:
  - bundle exec rspec
