language: ruby

sudo: false

addons:
  apt:
    sources:
      - zero-tsuki-ppa
    packages:
      - libapngasm
      - swig

rvm:
  - 2.0.0
  - 2.1
  - 2.2.3
  - ruby-head
  - rbx
  - jruby-head

script:
  - bundle exec rspec
